PREFIX i: <https://www.imi.med.fau.de/AllenSparql/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT { 

	?super i:hasSubInterval ?sub .
	?super i:hasValue ?avgValue .
	?super i:hasSubCount ?subCount .
  
} WHERE {
   	
	SELECT ?super (count(?sub) as ?subCount) (avg(?value) as ?avgValue) WHERE {
		
		?super i:hasSubInterval ?sub .
		?sub i:hasValue ?value .
	
	} group by ?super
  
}