-- After having imported the "MIMIC_I2B2" table into the i2b2 project schema, run this script. It transfers the data into the OBBSERVATION_FACT table
-- and also creates the i2b2 ontology.

DELETE FROM I2B2;

COMMIT;

INSERT INTO I2B2(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, VALUETYPE_CD, M_APPLIED_PATH, M_EXCLUSION_CD, C_PATH, C_SYMBOL) VALUES (0, '\i2b2\', 'i2b2', 'N', 'CA ', NULL, '', '', 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\', '', 'i2b2', sysdate, '', '', '', '@', '', '', '');

INSERT INTO I2B2(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, VALUETYPE_CD, M_APPLIED_PATH, M_EXCLUSION_CD, C_PATH, C_SYMBOL) 
SELECT DISTINCT 1, '\i2b2\'||CONCEPT||'\', CONCEPT, 'N', 'LAE', NULL, CONCEPT, '<?xml version="1.0" encoding="UTF-8"?><ValueMetadata><Version>3.2</Version><CreationDateTime>2010-11-17T20:21:04.486+01:00</CreationDateTime><Loinc>Unspecified</Loinc><UnitValues><NormalUnits>'||CONCEPT||' UNIT</NormalUnits></UnitValues><DataType>Float</DataType><Oktousevalues>Y</Oktousevalues></ValueMetadata>', 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\'||CONCEPT||'\', '', CONCEPT, sysdate, '', '', '', '@', '', '', ''
FROM MIMIC_I2B2;

COMMIT;

DELETE FROM CONCEPT_DIMENSION;

COMMIT;

INSERT INTO CONCEPT_DIMENSION (CONCEPT_CD, CONCEPT_PATH, NAME_CHAR, CONCEPT_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID) SELECT DISTINCT C_BASECODE, C_FULLNAME, C_NAME, null, null, null, null, null, null FROM I2B2 WHERE C_VISUALATTRIBUTES LIKE 'LA%';

TRUNCATE TABLE OBSERVATION_FACT;

INSERT INTO OBSERVATION_FACT(ENCOUNTER_NUM,PATIENT_NUM,CONCEPT_CD,PROVIDER_ID,START_DATE,MODIFIER_CD,INSTANCE_NUM,VALTYPE_CD,TVAL_CHAR,NVAL_NUM,VALUEFLAG_CD,QUANTITY_NUM,UNITS_CD,
END_DATE,LOCATION_CD,OBSERVATION_BLOB,CONFIDENCE_NUM,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,SOURCESYSTEM_CD,UPLOAD_ID)
SELECT DISTINCT PATIENT, PATIENT, CONCEPT, 'MIMIC-III', STARTTIME,'@',rownum,'N','E', VALUE,'',1,'UNITS_CD',ENDTIME,'LOCATION_CD','OBSERVATION_BLOB',0,
null,null,SYSDATE,'SOURCESYSTEM_CD','0' FROM MIMIC_I2B2;

COMMIT;
